<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- 指定父项目 -->
    <parent>
        <groupId>com.liyi</groupId>
        <artifactId>seckill-rag</artifactId>
        <version>${revision}</version>
    </parent>

    <!-- 指定打包方式 -->
    <packaging>jar</packaging>

    <artifactId>seckill-rag-order</artifactId>
    <name>${artifactId}</name>
    <description>订单模块，放置秒杀下单、订单列表、订单详情、取消订单、模拟支付等接口</description>

    <dependencies>
        <!-- 引入公共模块 -->
        <dependency>
            <groupId>com.liyi</groupId>
            <artifactId>seckill-rag-common</artifactId>
        </dependency>
    </dependencies>
</project>
