<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- 指定父项目 -->
    <parent>
        <groupId>com.liyi</groupId>
        <artifactId>seckill-rag</artifactId>
        <version>${revision}</version>
    </parent>

    <!-- 指定打包方式 -->
    <packaging>jar</packaging>

    <artifactId>seckill-rag-app</artifactId>
    <name>${artifactId}</name>
    <description>启动模块，负责整合所有业务模块</description>


    <dependencies>
        <!-- 引入订单模块 -->
        <dependency>
            <groupId>com.liyi</groupId>
            <artifactId>seckill-rag-order</artifactId>
        </dependency>

        <!-- 引入用户模块 -->
        <dependency>
            <groupId>com.liyi</groupId>
            <artifactId>seckill-rag-user</artifactId>
        </dependency>

        <!-- 引入商品模块 -->
        <dependency>
            <groupId>com.liyi</groupId>
            <artifactId>seckill-rag-goods</artifactId>
        </dependency>

        <!-- Spring Boot Test -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <!-- 排除默认的 Logback 日志框架 -->
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
