<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <!-- 指定父项目 -->
    <parent>
        <groupId>com.liyi</groupId>
        <artifactId>seckill-rag</artifactId>
        <version>${revision}</version>
    </parent>

    <!-- 指定打包方式 -->
    <packaging>jar</packaging>

    <artifactId>seckill-rag-user</artifactId>
    <name>${artifactId}</name>
    <description>用户模块，放置用户登录、注册、发送验证码等接口</description>

    <dependencies>
        <!-- 引入公共模块 -->
        <dependency>
            <groupId>com.liyi</groupId>
            <artifactId>seckill-rag-common</artifactId>
        </dependency>

        <!-- Spring Security Crypto（仅使用 BCrypt 密码加密，不引入完整 Spring Security） -->
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>

        <!-- 行为验证码 -->
        <dependency>
            <groupId>cloud.tianai.captcha</groupId>
            <artifactId>tianai-captcha-springboot-starter</artifactId>
        </dependency>
    </dependencies>
</project>
